const ADD_PERSON = 'ADD_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';
const ADD_WORK = 'ADD_WORK';
const DELETE_WORK = 'DELETE_WORK';
const ADD_AVALIACAO = 'ADD_AVALIACAO';
const DELETE_AVALIACAO = 'DELETE_AVALIACAO';
const ADD_USUARIO = 'ADD_USUARIO';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

export {
  ADD_PERSON,
  DELETE_PERSON,
  ADD_WORK,
  DELETE_WORK,
  ADD_AVALIACAO,
  DELETE_AVALIACAO,
  ADD_USUARIO,
  LOGIN,
  LOGOUT
};
