const ADD_PERSON = 'ADD_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';
const ADD_WORK = 'ADD_WORK';
const DELETE_WORK = 'DELETE_WORK';

export {
  ADD_PERSON,
  DELETE_PERSON,
  ADD_WORK,
  DELETE_WORK,
};
